### ISSUE TITLE
Improve login page design

### ISSUE THREAD

**Issue by Swanand01** [Swanand01/anton-LAN-storage#1]
Currently, the login page for ANTON is just a barebone HTML design. It should be changed to match the design of the other pages, e.g. the file index page.

The file to be edited is login.html inside templates/__autoindex__. The css file is autoindex.css in static.

**Comment by santoshdvc** [comment]
Can you please describe what content/elements do you need in the login page?

**Comment by Swanand01** [comment]
Hi!
I think we should have a Login text, below it a password field and then a login button. Similar to what we have right now.
We should just center it and enlarge it a bit maybe. Also change the button style.

**Comment by santoshdvc** [comment]
Okay. I am on it.

**Comment by Swanand01** [comment]
Thanks for your time and effort!
